config/routes.rb
Rails.application.routes.draw do
  resources :pet_histories
  resources :pets
  resources :clients
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :pet_histories
  belongs_to :Client
end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
    @pets = Pet.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:phone, :name, :email)
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: %i[ show edit update destroy ]

  # GET /pet_histories or /pet_histories.json
  def index
    @pet_histories = PetHistory.all.order('id ASC')
  end

  # GET /pet_histories/1 or /pet_histories/1.json
  def show
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
  end

  # GET /pet_histories/1/edit
  def edit
  end

  # POST /pet_histories or /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to pet_history_url(@pet_history), notice: "Pet history was successfully created." }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1 or /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to pet_history_url(@pet_history), notice: "Pet history was successfully updated." }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1 or /pet_histories/1.json
  def destroy
    @pet_history.destroy

    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: "Pet history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:height, :weight, :dateVisit, :diagnosis, :pet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all.order("name DESC")
    @pet_histories = PetHistory.all
  end

  # GET /pets/1 or /pets/1.json
  def show
    @pet_histories = PetHistory.all
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :race, :birthday, :Client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Phone:</strong>
    <%= client.phone %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h2>Editing client</h2>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="text-center">Clients</h2>
<%= link_to "New client", new_client_path %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Phone</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Pets Nbr.</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td><%= client.phone %></td>
      <td><%= client.name %></td>
      <td><%= client.email %></td>
      <td><%= client.pets.count() %></td>
      <td><%= link_to "Show", client %></td>
      <td><%= link_to "Edit", edit_client_path(client.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h2>New client</h2>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinarian</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pet_histories/_form.html.erb
<%= form_with(model: pet_history) do |form| %>
  <% if pet_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
        <% pet_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :dateVisit, style: "display: block" %>
    <%= form.date_field :dateVisit %>
  </div>

  <div>
    <%= form.label :diagnosis, style: "display: block" %>
    <%= form.text_field :diagnosis %>
  </div>

  <div>
    <%= form.label :pet_id, style: "display: block" %>
    <%= collection_select(:pet_history, :pet_id, Pet.all, :id, :name) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pet_histories/_pet_history.html.erb
<div id="<%= dom_id pet_history %>">
  <p>
    <strong>Height:</strong>
    <%= pet_history.height %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= pet_history.weight %>
  </p>

  <p>
    <strong>Datevisit:</strong>
    <%= pet_history.dateVisit %>
  </p>

  <p>
    <strong>Diagnosis:</strong>
    <%= pet_history.diagnosis %>
  </p>

  <p>
    <strong>Pet:</strong>
    <%= pet_history.pet.name %>
  </p>

</div>

app/views/pet_histories/edit.html.erb
<h1>Editing pet history</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Show this pet history", @pet_history %> |
  <%= link_to "Back to pet histories", pet_histories_path %>
</div>

app/views/pet_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="text-center">Pet histories</h2>
<%= link_to "New pet history", new_pet_history_path %>
<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Height</th>
      <th scope="col">Weight</th>
      <th scope="col">Datevisit</th>
      <th scope="col">Diagnosis</th>
      <th scope="col">Pet</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
  <% @pet_histories.each do |pet_history| %>
    <tr>
      <td><%= pet_history.height %></td>
      <td><%= pet_history.weight %></td>
      <td><%= pet_history.dateVisit %></td>
      <td><%= pet_history.diagnosis %></td>
      <td><%= pet_history.pet.name %></td>
      <td><%= link_to "Show", pet_history %></td>
      <td><%= link_to "Edit", edit_pet_history_path(pet_history.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/pet_histories/new.html.erb
<h1>New pet history</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Back to pet histories", pet_histories_path %>
</div>

app/views/pet_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet_history %>

<div>
  <%= link_to "Edit this pet history", edit_pet_history_path(@pet_history) %> |
  <%= link_to "Back to pet histories", pet_histories_path %>

  <%= button_to "Destroy this pet history", @pet_history, method: :delete %>
</div>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :race, style: "display: block" %>
    <%= form.text_field :race %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.label :Client_id, style: "display: block" %>
    <%= collection_select( :pet, :Client_id, Client.all, :id, :name )%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Name:</strong>
    <%= pet.name %>
  </p>

  <p>
    <strong>Race:</strong>
    <%= pet.race %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= pet.birthday %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= pet.Client.name %>
  </p>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Avg Weight</th>
      <th scope="col">Avg Height</th>
      <th scope="col">Max Weight</th>
      <th scope="col">Max Height</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= pet.pet_histories.average(:weight) %></td>
      <td><%= pet.pet_histories.average(:height) %></td>
      <td><%= pet.pet_histories.maximum(:weight) %></td>
      <td><%= pet.pet_histories.maximum(:height) %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/pets/edit.html.erb
<h2>Editing pet</h2>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Show this pet", @pet %> |
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="text-center">Pets</h2>
<%= link_to "New pet", new_pet_path %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Race</th>
      <th scope="col">Birthday</th>
      <th scope="col">Client</th>
      <th scope="col">Visits</th>

      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet| %>
    <tr>
      <td><%= pet.name %></td>
      <td><%= pet.race %></td>
      <td><%= pet.birthday %></td>
      <td><%= pet.Client.name %></td>
      <td><%= pet.pet_histories.count() %></td>
      <td><%= link_to "Show", pet %> </td>
      <td><%= link_to "Edit", edit_pet_path(pet.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pets/new.html.erb
<h2>New pet</h2>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", pets_path %>

  <%= button_to "Destroy this pet", @pet, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Pets", pets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pets History", pet_histories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Clients", clients_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>